server:
  port: 8089
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/clinic_appointment?createDatabaseIfNotExist=true} # &useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: ${MYSQL_ROOT_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        jdbc:
          useUnicode: true
          character_encoding: UTF-8
          connection:
            characterEncoding: UTF-8
        connection:
          CharSet: UTF-8
          useUnicode: true
          characterEncoding: utf8mb4
        dialect: org.hibernate.dialect.MySQLDialect
        connectionCollation: utf8mb4_unicode_ci
      format_sql: true

    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: false
    locations: classpath:/db/migration, classpath:/dev/db/migration
    baseline-version: 0
    baseline-on-migrate: true

hibernate:
  discriminator:
    ignore_explicit_for_joined: true


jwt:
  secret-key: "9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9"
  expiration: 86400 # 1 day = 60 * 60 * 24   giá trị đang ở seconds